layout_spectrum: 0.9492256070952863
typography_spectrum: 0.5035062907263637
color:
  brandStrength: 0.2627070883754641
  lightness: 0.535004276316613
  saturation: 0.18830164917744696
  rhythmicContrast: 0.07823116541840136
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
name: sandbox
